# User + Key Setup
- name: Create a new user with sudo privileges
  user:
    name: "{{ lookup('env', 'RUSER') }}"
    password: "{{ lookup('env', 'RUSER') }}"
    state: present
    groups: "{{ lookup('env', 'RGROUPS') }}"
    append: true
    create_home: true
    shell: /bin/zsh

- name: Set authorized key for new user
  authorized_key:
    user: "{{ lookup('env', 'RUSER') }}"
    state: present
    key: "{{ lookup('file', lookup('env','RKEY') + '.pub') }}"
