- hosts: all
  become: true
  tasks:
    - name: Make sure we have a 'wheel' group
      group:
        name: wheel
        state: present
    
    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'
    
    # User + Key Setup
    - name: Create a new user with sudo privileges
      user:
        name: "{{ lookup('env', 'ANSIBLE_USER') }}"
        state: present
        groups: wheel
        append: true
        create_home: true
        shell: /bin/bash
    
    - name: Set authorized key for ansible user
      authorized_key:
        user: "{{ lookup('env', 'ANSIBLE_USER') }}"
        state: present
        key: "{{ lookup('file', lookup('env','ANSIBLE_KEY') + '.pub') }}"
