- name: Add a user
  gather_facts: false
  hosts: all
  become: true
  tasks:
    - name: Create new user
      user:
        name: "{{user_name}}"
        groups: "{{user_groups.split()}}"
        shell: /bin/zsh
        state: present
        append: yes
        create_home: true
        skeleton: "/etc/skel"

    - name: Set authorized key for new user
      authorized_key:
        user: "{{user_name}}"
        state: present
        key: "{{user_key}}"
  vars:
    user_name: "{{ lookup('env', 'NUSER') }}"
    user_groups: "{{ lookup('env', 'NGROUPS') }}"
    user_key: "{{ lookup('file', lookup('env','NKEY') + '.pub') }}"
