- name: Add a user
  gather_facts: false
  hosts: all
  become: true
  tasks:
    - name: Create new user
      user:
        name: "{{user_name}}"
        groups: "{{user_groups.split()}}"
        shell: /bin/zsh
        state: present
        append: yes
        create_home: true
        skeleton: "/etc/skel"

    - name: Set authorized key for new user
      authorized_key:
        user: "{{user_name}}"
        state: present
        key: "{{user_key}}"

    - name: Set user to automatically load ROS variables (ZSH)
      become: true
      become_user: "{{ user_name }}"
      lineinfile:
        path: ~/.zshrc
        regexp: '/opt/ros/{{ros_release}}/setup.zsh$'
        line: '[ -f /opt/ros/{{ros_release}}/setup.zsh ] && source /opt/ros/{{ros_release}}/setup.zsh'

    - name: Set user to automatically load ROS variables (Bash)
      become: true
      become_user: "{{ user_name }}"
      lineinfile:
        path: ~/.bashrc
        regexp: '/opt/ros/{{ros_release}}/setup.bash$'
        line: '[ -f /opt/ros/{{ros_release}}/setup.bash ] && source /opt/ros/{{ros_release}}/setup.bash'

  vars:
    user_name: "{{ lookup('env', 'NUSER') }}"
    user_groups: "{{ lookup('env', 'NGROUPS') }}"
    user_key: "{{ lookup('file', lookup('env','NKEY') + '.pub') }}"
    ros_release: "{{ lookup('env', 'ROS_RELEASE') }}"
